### ISSUE TITLE
ARM Support

### ISSUE THREAD

**Issue by jlamande** [bitnami/bitnami-docker-postgresql#327] opened 2022-02-21 07:50 UTC
### Name and Version

bitnami/postgresql

### What is the problem this feature will solve?

Docker image is published in linux/amd64 architecture only.

Please build and publish a multi-architecture image with at least linux/arm64/v8

### What is the feature you are proposing to solve the problem?

Using `docker buildx` command provides simplified builds and publications for multiple architectures.

**Comment by juan131** [comment] 2022-02-21 07:55
Closing as duplicate of https://github.com/bitnami/charts/issues/7305

**Closed by juan131** 2022-02-21 07:55 UTC
