### ISSUE TITLE
Postgresql 10.7.0 Docker Image Update is Broken 

### ISSUE THREAD

**Issue by igdianov** [bitnami/bitnami-docker-postgresql#134] opened 2019-05-09 19:54 UTC
**Description**

There is something changed in the Postgresql 10.7.0 image after update 4 hours ago that causes permission error that prevents Postgresql container startup in Kubernetes:

```
INFO  ==> ** Starting PostgreSQL **
2019-05-09 16:01:39.194 GMT [1] LOG:  skipping missing configuration file "/bitnami/postgresql/postgresql.auto.conf"
2019-05-09 16:01:39.194 GMT [1] FATAL:  data directory "/bitnami/postgresql" has group or world access
2019-05-09 16:01:39.194 GMT [1] DETAIL:  Permissions should be u=rwx (0700).
```
https://hub.docker.com/r/bitnami/postgresql/tags:

![image](https://user-images.githubusercontent.com/20428629/57482529-b2dd1580-7259-11e9-8945-0e2413acc848.png)

**Steps to reproduce the issue:**

```
helm install stable/postgresql \
    --set postgresqlPassword=password  \
    --version 3.11.3
```

**Describe the results you received:**

```
INFO  ==> ** Starting PostgreSQL setup **
INFO  ==> Validating settings in POSTGRESQL_* env vars..
INFO  ==> Initializing PostgreSQL database...
INFO  ==> postgresql.conf file not detected. Generating it...
INFO  ==> pg_hba.conf file not detected. Generating it...
INFO  ==> Deploying PostgreSQL with persisted data...
INFO  ==> Configuring replication parameters
INFO  ==> Loading custom scripts...
INFO  ==> Enabling remote connections
INFO  ==> Stopping PostgreSQL...
INFO  ==> ** PostgreSQL setup finished! **

INFO  ==> ** Starting PostgreSQL **
2019-05-09 16:01:39.194 GMT [1] LOG:  skipping missing configuration file "/bitnami/postgresql/postgresql.auto.conf"
2019-05-09 16:01:39.194 GMT [1] FATAL:  data directory "/bitnami/postgresql" has group or world access
2019-05-09 16:01:39.194 GMT [1] DETAIL:  Permissions should be u=rwx (0700).
```

**Describe the results you expected:**

```
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql            
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql/issues        
                                                                                                         
nami    INFO  Initializing postgresql                                                                    
postgre INFO  ==> No injected postgresql.conf file found. Creating default postgresql.conf file...       
postgre INFO  ==> No injected pg_hba.conf file found. Creating default pg_hba.conf file...               
postgre INFO  ==> Deploying PostgreSQL from scratch...                                                   
postgre INFO  ==> Creating postgres user with unrestricted access...                                     
postgre INFO  ==> Configuring PostgreSQL...                                                              
postgre INFO  ==> Configuring replication parameters...                                                  
postgre INFO  ==> Configuring permissions for config files...                                            
postgre INFO                                                                                             
postgre INFO  ########################################################################                   
postgre INFO   Installation parameters for postgresql:                                                   
postgre INFO     Root User: postgres                                                                     
postgre INFO     Password: **********                                                                    
postgre INFO   (Passwords are not shown for security reasons)                                            
postgre INFO  ########################################################################                   
postgre INFO                                                                                             
nami    INFO  postgresql successfully initialized                                                        
INFO  ==> Starting postgresql...                                                                         
2019-05-09 18:20:57.724 GMT [123] LOG:  listening on IPv4 address "0.0.0.0", port 5432                   
2019-05-09 18:20:57.724 GMT [123] LOG:  listening on IPv6 address "::", port 5432                        
2019-05-09 18:20:57.727 GMT [123] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"                    
2019-05-09 18:20:57.737 GMT [130] LOG:  database system was shut down at 2019-05-09 18:20:57 GMT         
2019-05-09 18:20:57.741 GMT [123] LOG:  database system is ready to accept connections                   
```

**Additional information you deem important (e.g. issue happens only occasionally):**

I have an older Postgresql:10.7.0 image from a few days ago that I used to override latest broken image and it works.. 

**Version**

- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

AWS EKS

**Comment by maslick** [comment] 2019-05-09 20:02
I'm experiencing the same problem :(

**Comment by bakerm645** [comment] 2019-05-10 00:07
Rolling back to version `10.7.0-r68` has resolved the issue for me. 
Tried `10.7.0-r69`, but encountered the same issue.

**Comment by igdianov** [comment] 2019-05-10 01:30
It is against common sense and best practices to break immutability of the published Docker images. The update should have used different tag. This problem affects anyone who uses published Postgresql Docker image directly or indirectly via Helm charts.

**Comment by coswind** [comment] 2019-05-10 04:08
I have the same problem.

**Comment by alphabt** [comment] 2019-05-10 04:45
@bakerm645 is right. Also for `10.7.0-r69` or above use chart `4.0.0` or above per  https://github.com/helm/charts/issues/13651#issuecomment-490926979

**Comment by juan131** [comment] 2019-05-10 06:40
Hi everyone,

As described on the "Upgrade section" of the PostgreSQL chart below, you should upgrade to the version **4.0.0** or greater of the chart to use the version **10.7.0-r69** or greater of the Docker image.

https://github.com/helm/charts/tree/master/stable/postgresql#400

You should be able to upgrade the chart by running the commands below (please note the commands below assumed you named your release 'my-release'):

```bash
$ helm install stable/postgresql --name my-release \
     --version 3.15.0 \
     --set image.tag=10.7.0-r68 \
     --set postgresqlPassword=my-password \
     --set postgresqlDatabase=my-database
$ export POSTGRES_PASSWORD=$(kubectl get secret --namespace default my-release-postgresql -o jsonpath="{.data.postgresql-password}" | base64 --decode)
$ helm upgrade my-release stable/postgresql \
     --version 4.0.1 \
     --set image.tag=10.7.0-r71 \
     --set postgresqlPassword=$POSTGRES_PASSWORD \
     --set postgresqlDatabase=my-database
```

On the other hand, you **should not be using rolling tags on production**. You can find more information in the link below:

https://docs.bitnami.com/containers/how-to/understand-rolling-tags-containers

**Comment by igdianov** [comment] 2019-05-10 07:18
@juan131 This does makes sense in retrospect, but in practice there is an immutable Posgresql Helm chart v3.11.3 published by Bitnami that uses 10.7.0 rolling tag inside values.yaml. This chart is embedded in other immutable published Helm charts that are broken now. Besides, no one reads about rolling tags for containers and there is no mention about it in:  https://github.com/helm/charts/tree/master/stable/postgresql

Is there a plan to fix broken Postgresql Docker image 10.7.0?

**Comment by juan131** [comment] 2019-05-10 10:43
Hi everyone,

We shouldn't have included a breaking change on a rolling tag to avoid breaking the chart. We apologize for this error and we'll work on improving the documentation so everyone understand the implications on using rolling tags.

We just created a PR to address this issue and release new revisions of the images that will be compatible both with Helm Chart 3.x.x and 4.x.x versions.

We're also opening an internal retrospective to reconsider our tag policies, so we can find a way to improve the images without affecting users.

We really appreciate your collaboration and please, do hot hesitate to report us any issue you may find.

Sorry for the inconveniences.

**Comment by juan131** [comment] 2019-05-10 11:19
We just merged the changes and I triggered the release process. I'll update this issue once the images are released. Thanks for you consideration and patience.

**Closed** 2019-05-10 11:19 UTC

**Comment by juan131** [comment] 2019-05-10 11:51
Hi everyones,

We just released new revisions that are compatible with both **3.x.x** and **4.x.x** charts:

- 9.6 series: **9.6.12-r73**
- 10 series: **10.7.0-r72**
- 11 series: **11.2.0-r73**

It should be safe from now on to continue using the rolling tags but, as it's explained in the link below, it's not a recommended option for production environments:

https://docs.bitnami.com/containers/how-to/understand-rolling-tags-containers

Please do not hesitate to let us know if you face any issue with these new images.

**Comment by igdianov** [comment] 2019-05-10 13:59
@juan131 Thank you very much!

**Comment by erniux** [comment] 2019-08-01 02:43
Thank you great Job!

**Comment by juan131** [comment] 2019-10-15 08:13
Hi @zarkin 

What version of the PostgreSQL chart and what version of the Bitnami PostgreSQL image are you using? 
Did you reproduce the issue by running `helm upgrade `... or any other equivalent command?

**Comment by zarkin** [comment] 2019-10-15 13:22
I've encountered the issue using tag 10.7.0-r72 and r73. I'm using docker-compose, and not helm to create the container. I think I've found my issue. The .dockerfile I'm using is as follows:

```
FROM bitnami/postgresql:10.7.0-r73
#USER root
COPY ./postgresql.conf /bitnami/postgresql/conf/
RUN apt-get update && apt-get -y install git make gcc \
    && git clone https://github.com/citusdata/pg_cron.git \
    && cd pg_cron && PATH=$PATH make install && cd ../
```
docker-compose.yml:
``` 
version: '2.4'

services:

  postgres:
   build: "./postgres"
   #user: root #This seems to have no effect
   networks:
      - meqnet
   environment:
      POSTGRESQL_PASSWORD: PASSWORD #Not the actual password I'm using.
   #volumes: Trying
   #- D:\PersonalRepos\MoneyPeer\MoneyPeerDeployment\postgrespersistence:/bitnami/postgresql
  
networks:
  meqnet:
    driver: bridge      
```  


I can't execute the run command without using the root user as I encounter the following error:
 List directory /var/lib/apt/lists/partial is missing. - Acquire (2: No such file or directory).

If I set user to root in the .dockerfile, I can build the container, but it immediately crashes upon startup with the following error logs:

Welcome to the Bitnami postgresql container
postgres_1  | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql
postgres_1  | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql/issues
postgres_1  | Send us your feedback at containers@bitnami.com
postgres_1  |
postgres_1  | INFO  ==> ** Starting PostgreSQL setup **
postgres_1  | INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgres_1  | postgresql:x:1000:
postgres_1  | INFO  ==> Initializing PostgreSQL database...
postgres_1  | INFO  ==> Custom configuration /opt/bitnami/postgresql/conf/postgresql.conf detected
postgres_1  | INFO  ==> pg_hba.conf file not detected. Generating it...
postgres_1  | INFO  ==> Stopping PostgreSQL...
postgres_1  |
postgres_1  | Welcome to the Bitnami postgresql container
postgres_1  | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql
postgres_1  | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql/issues
postgres_1  | Send us your feedback at containers@bitnami.com
postgres_1  |
postgres_1  | INFO  ==> ** Starting PostgreSQL setup **
postgres_1  | INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgres_1  | INFO  ==> Initializing PostgreSQL database...
postgres_1  | INFO  ==> Custom configuration /opt/bitnami/postgresql/conf/postgresql.conf detected
postgres_1  | INFO  ==> pg_hba.conf file not detected. Generating it...
postgres_1  | INFO  ==> Deploying PostgreSQL with persisted data...
postgres_1  | INFO  ==> Loading custom scripts...
postgres_1  | INFO  ==> Stopping PostgreSQL...
postgres_1  |
postgres_1  | INFO  ==> ** PostgreSQL setup finished! **
postgres_1  | INFO  ==> ** Starting PostgreSQL **
postgres_1  | 2019-10-15 13:19:06.924 GMT [1] LOG:  skipping missing configuration file "/bitnami/postgresql/data/postgresql.auto.conf"
postgres_1  | 2019-10-15 13:19:06.927 GMT [1] FATAL:  data directory "/bitnami/postgresql/data" has group or world access
postgres_1  | 2019-10-15 13:19:06.927 GMT [1] DETAIL:  Permissions should be u=rwx (0700).

I'm using docker for windows: Engine version 19.03.2,  and docker-compose 1.24.1

**Comment by juan131** [comment] 2019-10-16 07:28
Hi @igdianov 

The Bitnami PostgreSQL is a "non-root" container and it's not guaranteed to work when running it as "root". If you want to install extra-packages on your image, you can use the workaround below:

```Dockerfile
FROM bitnami/postgresql
USER root
# Privileges actions
RUN install_packages xxx yyy zzz...
...
# Return back to the user 1001
USER 1001
```

Please note that I'm using `install_packages` instead of `apt-get ...` since it's a wrapper we include that performs some performance improvements (such as cleaning the cache after installing the packages)

**Comment by zarkin** [comment] 2019-10-16 12:46
Thanks, I'll try that.

**Comment by juan131** [comment] 2019-10-16 13:11
Great! Please let us know if you find any issue @zarkin

**Comment by zarkin** [comment] 2019-10-16 13:33
Seems to be working fine. Thanks for your help.

**Comment by juan131** [comment] 2019-10-16 14:18
You're welcome! I'm glad you solved the issue.
