### ISSUE TITLE
Helm Chart - EACCES: permission denied

### ISSUE THREAD

**Issue by karaktaka** [bitnami/bitnami-docker-postgresql#92] opened 2018-11-06 15:02 UTC
**Description**

Helm Chart uploads Postgresql to k8s, but fails with Permission denied error, although there is a chown container present.

**Steps to reproduce the issue:**

1. Install Postgresql via Helm onto k8s with persistent storage

**Describe the results you received:**

```
nami    INFO  Initializing postgresql
postgre INFO  ==> No injected postgresql.conf file found. Creating default postgresql.conf file...
postgre INFO  ==> No injected pg_hba.conf file found. Creating default pg_hba.conf file...
postgre INFO  ==> Deploying PostgreSQL from scratch...
Error executing 'postInstallation': EACCES: permission denied, mkdir '/bitnami/postgresql/data'
```

**Describe the results you expected:**

Postgresql should install and start without any problems

**Additional information you deem important (e.g. issue happens only occasionally):**

The init-chown-container only changes permissions, if there is a "data"-folder present, which is not, if it runs before the postgresql container. Even after creating and changing permissions on the folder manually it doesn't seem to work.

**Version**

- Output of `docker version`:

```
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 01:35:00 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 01:35:00 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

- Output of `docker info`:

```
Containers: 18
 Running: 15
 Paused: 0
 Stopped: 3
Images: 20
Server Version: 17.03.2-ce
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.14.73-rancher
Operating System: RancherOS v1.4.2
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.67 GiB
Name: worker-node1
ID: T3WR:WCFF:NYNL:3PLO:JGIJ:5L3R:DTMC:TDXS:SUT2:IPGI:FRV5:XBSX
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
 provider=vmwarevsphere
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
- Helm Chart Version: 2.3.0
- Postgresql App Version: 10.5.0

**Comment by tompizmor** [comment] 2018-11-07 08:35
Duplicate of #91

**Closed** 2018-11-07 08:35 UTC
